import {ensureSchema,eventDb,getEventPresentation} from '../api/leads/_shared.js';

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nl(v){return esc(v).replace(/\n/g,'<br>')}
function floridaNow(){
  const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());
  const o={};for(const x of p)if(x.type!=='literal')o[x.type]=x.value;
  return {date:`${o.year}-${o.month}-${o.day}`,time:`${o.hour}:${o.minute}`};
}
function ended(e){const n=floridaNow();return Number(e.archived)||!Number(e.enabled)||n.date>e.event_date||(n.date===e.event_date&&n.time>e.end_time)}
function fmtDate(v){try{return new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'America/New_York'}).format(new Date(v+'T12:00:00-04:00'))}catch{return v}}

export async function onRequestGet({params,env}){
  if(!await ensureSchema(env))return new Response('Service unavailable',{status:503});
  const slug=String(params.slug||'').toLowerCase().trim();
  const event=await eventDb(env).prepare('SELECT event_key,name,slug,event_date,start_time,end_time,enabled,archived,confirmation_enabled FROM lead_events WHERE slug=? LIMIT 1').bind(slug).first();
  if(!event)return new Response('Event not found',{status:404});
  const p=await getEventPresentation(env,event.event_key);
  const isEnded=ended(event);
  const title=p.public_headline|| (p.show_event_name?event.name:'Connect With F45');
  const sub=p.show_event_name&&p.public_headline?event.name:'';
  const infoTitle=p.info_title||'F45 POMPANO BEACH';
  const infoBody=p.info_body||'Enter your information below to connect with our team.';
  const confirmation=p.confirmation_message||'Thanks for connecting with F45 Training Pompano Beach.';
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#1C1C2E"><title>${esc(title)} · F45 Pompano Beach</title>
  <style>
  :root{--navy:#1C1C2E;--red:#E8272A;--yellow:#FFB800;--ink:#20202b;--muted:#6b7280;--bg:#f5f6f8}
  *{box-sizing:border-box}html,body{margin:0;overflow-x:hidden;font-family:Inter,Arial,sans-serif;color:var(--ink);background:var(--bg)}a{color:inherit}
  .top{background:var(--navy);color:#fff;border-bottom:1px solid rgba(255,255,255,.12);position:sticky;top:0;z-index:10}.topin{max-width:1120px;margin:auto;padding:12px 18px;display:flex;align-items:center;justify-content:space-between;gap:16px}.brand{display:flex;align-items:center;gap:12px;font-weight:900}.brand img{height:46px;width:auto}.brand span{font-size:12px;letter-spacing:.08em}.nav{font-size:12px;font-weight:900;text-transform:uppercase;text-decoration:none;color:#fff}
  .hero{position:relative;min-height:520px;background:#111;display:grid;place-items:center;overflow:hidden}.hero video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.5}.shade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.1),rgba(0,0,0,.5))}
  .heroCard{position:relative;z-index:2;width:min(650px,92vw);text-align:center;color:#fff;background:rgba(8,10,18,.80);border:3px solid var(--red);border-radius:20px;padding:44px 28px;box-shadow:0 0 28px rgba(232,39,42,.45)}.heroCard h1{margin:0;font-size:clamp(38px,8vw,68px);line-height:.98;text-transform:uppercase;font-weight:950}.heroCard .sub{margin-top:12px;font-size:20px;font-weight:800}.heroCard .date{margin-top:14px;font-size:14px;color:#eceef4}
  .wrap{max-width:1000px;margin:auto;padding:30px 18px}.info{background:var(--yellow);border-radius:16px;padding:24px;text-align:center;box-shadow:0 10px 28px rgba(0,0,0,.10)}.info h2{margin:0 0 8px;font-size:28px;text-transform:uppercase}.info p{margin:0;line-height:1.55;font-weight:700}
  .formCard{margin-top:24px;background:#fff;border-radius:18px;box-shadow:0 16px 44px rgba(0,0,0,.10);overflow:hidden}.formHead{background:var(--navy);color:#fff;padding:24px;text-align:center;border-bottom:5px solid var(--red)}.formHead h2{margin:0;font-size:30px}.formHead p{margin:8px 0 0;color:#d9dcec}
  form{padding:24px;display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{display:flex;flex-direction:column;gap:6px}.full{grid-column:1/-1}.field label{font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.07em}.field input{font-size:16px;padding:13px;border:2px solid #c7ccd5;border-radius:9px}.consent{grid-column:1/-1;display:flex;gap:10px;align-items:flex-start;padding:12px;border:1px solid #d6d9df;border-radius:10px;background:#f8f9fb;font-size:12px;line-height:1.45}.consent input{width:18px;height:18px;flex:0 0 18px;accent-color:var(--red)}button.submit{grid-column:1/-1;background:var(--red);color:#fff;border:0;border-radius:9px;padding:16px;font-size:15px;font-weight:900;text-transform:uppercase}.fine{grid-column:1/-1;text-align:center;font-size:11px;color:var(--muted)}
  .success{display:none;padding:36px;text-align:center}.success.show{display:block}.success .icon{width:76px;height:76px;border-radius:50%;display:grid;place-items:center;margin:0 auto 14px;background:#edf9f0;font-size:36px}.success h2{margin:0 0 10px;color:var(--navy);font-size:30px}.success p{max-width:520px;margin:6px auto;line-height:1.55;color:#4b5563}.error{display:none;margin:0 24px 24px;padding:12px;background:#fff0f0;color:#9b1c1c;border-radius:8px}.error.show{display:block}
  .section{margin-top:32px;background:#fff;border-radius:16px;padding:28px;box-shadow:0 8px 24px rgba(0,0,0,.07)}.section h2{margin:0 0 18px;text-align:center;font-size:30px;color:var(--navy)}.schedule{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.day{border:1px solid #e5e7eb;border-radius:12px;padding:16px}.day b{display:block;color:var(--red);margin-bottom:7px}.day span{font-size:13px;line-height:1.45;color:#4b5563}.expect{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.expect div{background:#f7f8fb;border-radius:12px;padding:18px;text-align:center}.expect b{display:block;margin-bottom:6px}.reviews{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.review{border:1px solid #e5e7eb;border-radius:12px;padding:18px;line-height:1.5}.stars{color:#f5a623;font-size:18px;letter-spacing:2px}.ended{max-width:700px;margin:70px auto;background:#fff;border-radius:18px;padding:42px 28px;text-align:center;box-shadow:0 14px 40px rgba(0,0,0,.1)}.ended h1{font-size:42px;margin:0 0 12px}.ended a{display:inline-block;margin-top:18px;background:var(--red);color:#fff;text-decoration:none;padding:13px 18px;border-radius:8px;font-weight:900}
  .footer{text-align:center;padding:26px 16px 36px;color:#6b7280;font-size:12px}
  @media(max-width:700px){.brand span{display:none}.hero{min-height:440px}.heroCard{padding:34px 20px}.wrap{padding:20px 10px}form{grid-template-columns:1fr;padding:18px}.field{grid-column:1/-1}.schedule,.expect,.reviews{grid-template-columns:1fr}.section{padding:22px 16px}.info{padding:20px 16px}}
  </style></head><body>
  <header class="top"><div class="topin"><div class="brand"><img src="/f45-pompano-logo-white.svg" alt="F45 Pompano Beach" onerror="this.style.display='none'"><span>F45 POMPANO BEACH</span></div><a class="nav" href="/">Main Site</a></div></header>
  ${isEnded?`<main class="ended"><h1>EVENT ENDED</h1><p>This event is no longer accepting entries.</p><a href="/">Visit F45 Pompano Beach</a></main>`:`
  <section class="hero"><video autoplay muted loop playsinline src="/trial-video.mp4"></video><div class="shade"></div><div class="heroCard"><h1>${esc(title)}</h1>${sub?`<div class="sub">${esc(sub)}</div>`:''}<div class="date">${esc(fmtDate(event.event_date))}</div></div></section>
  <main class="wrap"><section class="info"><h2>${esc(infoTitle)}</h2><p>${nl(infoBody)}</p></section>
  <section class="formCard"><div class="formHead"><h2>Enter Your Info</h2><p>${event.confirmation_enabled?'You’ll receive a text to verify your entry.':'Connect with the F45 Pompano Beach team.'}</p></div>
  <form id="leadForm" novalidate>
  <div class="field"><label for="fn">First Name</label><input id="fn" autocomplete="given-name" required maxlength="40"></div><div class="field"><label for="ln">Last Name</label><input id="ln" autocomplete="family-name" required maxlength="40"></div>
  <div class="field full"><label for="em">Email</label><input id="em" type="email" autocomplete="email" required></div><div class="field"><label for="ph">Mobile Number</label><input id="ph" type="tel" autocomplete="tel" required></div><div class="field"><label for="zp">Home ZIP Code</label><input id="zp" inputmode="numeric" maxlength="5" required></div>
  <input id="web" style="position:absolute;left:-9999px" tabindex="-1" autocomplete="off">
  <label class="consent"><input id="cc" type="checkbox" required><span>I agree that F45 Training Pompano Beach may contact me by call or text about this inquiry or event entry. Message and data rates may apply. Reply STOP to opt out.</span></label>
  <label class="consent"><input id="tc" type="checkbox" required><span>I agree to the <a href="/terms/" target="_blank">Terms &amp; Conditions</a> and acknowledge the <a href="/privacy/" target="_blank">Privacy Policy</a>.</span></label>
  <label class="consent"><input id="mk" type="checkbox"><span>I agree to receive recurring customer care and marketing text messages from F45 Training Pompano Beach. Consent is not a condition of purchase. Reply STOP to opt out.</span></label>
  <button class="submit" id="submitBtn" type="submit">Submit</button><div class="fine">Your information is kept with F45 Training Pompano Beach and organized by this event.</div></form>
  <div class="error" id="error"></div><div class="success" id="success"><div class="icon">✓</div><h2 id="successTitle">You're All Set!</h2><p id="successText"></p><p id="customConfirm"></p></div></section>
  ${p.show_schedule?`<section class="section"><h2>Class Schedule</h2><div class="schedule"><div class="day"><b>MON / WED / FRI</b><span>Strength training throughout the day.</span></div><div class="day"><b>TUE / THU</b><span>Cardio-focused training, with HYROX sessions on select days.</span></div><div class="day"><b>SUNDAY</b><span>Hybrid training combining strength and conditioning.</span></div></div></section>`:''}
  ${p.show_expect?`<section class="section"><h2>What To Expect</h2><div class="expect"><div><b>Coach-Led</b><span>Our coaches guide you through every station.</span></div><div><b>45 Minutes</b><span>Efficient, structured training built for all fitness levels.</span></div><div><b>Team Training</b><span>A supportive group environment without the guesswork.</span></div></div></section>`:''}
  ${p.show_reviews?`<section class="section"><h2>Why Members Love F45</h2><div class="reviews"><div class="review"><div class="stars">★★★★★</div><p>“This gym has been an amazing experience for the past year. With the encouragement of the coaches I kept going even when things got hard. Since starting last March I've dropped 27 pounds of fat.”</p></div><div class="review"><div class="stars">★★★★★</div><p>“My husband and I started going here last year. As of this date we both have lost about 45lbs together. The workouts are fun and the environment is friendly.”</p></div><div class="review"><div class="stars">★★★★★</div><p>“After trying F45 studios in Pompano, Coral Ridge, and Cove, this location stands out as the best. The energy, the coaching, the community — everything here is a level above.”</p></div></div></section>`:''}
  </main>
  <script>(function(){const $=id=>document.getElementById(id),f=$('leadForm'),b=$('submitBtn'),err=$('error'),ok=$('success');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();err.classList.remove('show');if(!f.reportValidity())return;const zip=$('zp').value.trim();if(!/^\\d{5}$/.test(zip)){err.textContent='Please enter a valid 5-digit ZIP code.';err.classList.add('show');return}b.disabled=true;b.textContent='Saving...';try{const r=await fetch('/api/leads/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({first_name:$('fn').value.trim(),last_name:$('ln').value.trim(),email:$('em').value.trim(),phone:$('ph').value.trim(),zip,website:$('web').value,contact_consent:$('cc').checked,terms_accepted:$('tc').checked,marketing_opt_in:$('mk').checked,event:${JSON.stringify(slug)}})}),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.message||'Could not save your information.');f.style.display='none';if(j.confirmation_required){$('success').querySelector('.icon').textContent='📱';$('successTitle').textContent='Check Your Phone';$('successText').textContent='We sent you a confirmation text from F45 Pompano Beach. Tap the link in that text to verify your entry.'}else{$('successTitle').textContent="You're All Set!";$('successText').textContent='Your information was submitted successfully.'}$('customConfirm').textContent=${JSON.stringify(confirmation)};ok.classList.add('show');ok.scrollIntoView({behavior:'smooth',block:'center'})}catch(x){err.textContent=x.message||'Could not save your information.';err.classList.add('show')}finally{b.disabled=false;b.textContent='Submit'}})})();</script>`}
  <footer class="footer">F45 Training Pompano Beach · 824 N Federal Hwy, Pompano Beach, FL</footer></body></html>`;
  return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
}